### ISSUE TITLE
Can't start the container

### ISSUE THREAD

**Issue by rugebiker** [PauloASilva/TomTomSportsConnect#1]
Hi! First of all, thanks for making this :)

I just cloned the repo and now I have a problem when I try to run it. So after writing `xhost +` then I write:
`./TomTomSportsConnect`
and some kind of hash gets printed but I see nothing else happening.

I also try writing the `docker run..` command and in this case I get the following message:

> docker: invalid reference format: repository name must be lowercase.

Any idea what might be the problem? Thanks!

Running Fedora 28 with KDE.
The docker daemon is running correctly.

**Comment by rugebiker** [comment]
I tried to run it exactly the same in a fresh Mint install in virtualbox, and I got exactly the same problems as described above. =/

**Comment by PauloASilva** [comment]
Hi @rugebiker,
Thanks for your feedback.

I am running this on Fedora 28 with Gnome 3.x
I have no clue about what's wrong but I will try it in a virtual environment as yours.

Please check `$DISPLAY` env variable value.

Regards,
Paulo A. Silva

**Comment by PauloASilva** [comment]
Hi @rugebiker,
I was able to reproduce the reported problem on my own environment.

I did not publish the docker image due to possible legal issue but now the build step is broken. I'll have a look on it as soon as possible.

Cheers,
Paulo A. Silva

**Comment by rugebiker** [comment]
Thanks for looking into it :) If you need help testing it let me know!

Regards,
Ruben

**Comment by PauloASilva** [comment]
Hi @rugebiker ,
Sorry about the delay.

I was checking and you will be able to run [v0.1.0](https://github.com/PauloASilva/TomTomSportsConnect/releases/tag/v0.1.0): just download or checkout this specific version and follow the instructions.

The only difference between v0.1.0 and v0.2.0 is the docker base image: in v0.2.0 I have changed docker container base image to get a smaller resulting image.

In the meanwhile I'll try to fix v0.2.0.

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
Hi @rugebiker,
In [v0.3.0][1] I did rollback to phusion/baseimage as docker base image.

You should now be able to build the `master` branch: clone the repo and run 

```
$ docker build -t tomtomsc:latest .
```

Cheers,
Paulo A. Silva

[1]: https://github.com/PauloASilva/TomTomSportsConnect/releases/tag/v0.3.0
