### ISSUE TITLE
Container runs with UTC - time zone of watch will be overwritten

### ISSUE THREAD

**Issue by railfox** [PauloASilva/TomTomSportsConnect#4]
Currently, docker image will be built with UTC time zone.
Unfortunately, time zone of watch will be inherited from operating system during sync,
hence people with other time zone than UTC will have wrong time zone on the watch.

I've fixed this with  adaption of host system's time zone:

enhancement in docker file:
# inherit timezone from host system
ARG LOCALTIMEZONE
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -f tzdata
RUN echo $LOCALTIMEZONE
RUN ln -fs $LOCALTIMEZONE /etc/localtime
#RUN dpkg-reconfigure --frontend noninteractive tzdata

change of docker build command:
docker build --build-arg LOCALTIMEZONE=`file /etc/localtime | cut -d" " -f5` -t tomtomsc:latest .

I could do a pull request - but I'm not sure if my solution works on every distribution (tested with Debian /9 and Mint / 18) - I'm not so familiar with tzdata.

Cheers,
Martin

**Comment by PauloASilva** [comment]
Hey @railfox,
this is great!

Please open a Pull Request.
If some changes are required than we discuss them, improving the PR

Thanks for you contribution,
Paulo A. Silva

**Comment by railfox** [comment]
I've commited changed files in my fork. 
I guess this should extend the original pull request.

If this is right, issue could be closed.
(If not, I have to search the github manual - I didn't found a way to create a dedicated pull request with my fork.)

**Comment by PauloASilva** [comment]
This is fixed in [v0.3.0][1].

[1]: https://github.com/PauloASilva/TomTomSportsConnect/releases/tag/v0.3.0
