### ISSUE TITLE
Container cannot connect to internet

### ISSUE THREAD

**Issue by lcarlier** [PauloASilva/TomTomSportsConnect#6]
Hi,
this is actually not a bug report but a question.
On my Linux LTS 18.04 pc, I had to use the --network=host with the docker build command and also add that parameter to the TomTomSportConnect script that you've made.
How come should I do that?
Is it dangerous to use --network-host?
Kind regards,
Laurent

**Comment by PauloASilva** [comment]
Ho @lcarlier,
Thank you for your feedback.

The container itself does not start any services so you won't have port binding conflicts.
Sharing the host network will make local services available to the container: I don't see this as a huge problem, but usually I prefer to have containers isolated.

Regarding the connectivity problem, please check your firewall rules: it may be preventing containers to reach Internet.

You'll easily find some other common problems. Please check these:

* [Docker host need to have IP Forwarding enabled][1]
* [I can't get Docker containers to access the internet?][2]
* [lxc-docker startup script fails to set up iptables MASQ rule; WAS: dns issues while using docker run -dns][3]

Cheers,
Paulo A. Silva

[1]: https://github.com/moby/moby/issues/490 
[2]: https://stackoverflow.com/questions/23810845/i-cant-get-docker-containers-to-access-the-internet
[3]: https://github.com/moby/moby/issues/866
